### ISSUE TITLE
Input Validation error when input string ends with `==`

### ISSUE THREAD

**Issue by karanpopat** [turbot/flowpipe#126]
I’ve got this string input in pipeline -  
`"teamwork_tag_id=ZmRkYjNkMDQtYWQ2MS00YjBjLWFmNWEtMjkzMmEyNzdkMmJjIyM2ZWIwOWYwMi03NDVmLTQ0MGUtYmMxNi04MDQ4YmQwNjEwOGYjI3RxYlY2T2RlUw=="`

I get an error Error: Pipeline argument validation failed
It is because of the `==` at the end of the input string. It works if I remove == from the end(I mean the pipeline works, but the action fails because of the wrong input)
It also works when I set the same string as default in my param block.
```
flowpipe pipeline run create_tag  --pipeline-arg team_id="6eb09f02-745f-440e-bc16-8048bd06108f" --pipeline-arg teamwork_tag_id="ZmRkYjNkMDQtYWQ2MS00YjBjLWFmNWEtMjkzMmEyNzdkMmJjIyM2ZWIwOWYwMi03NDVmLTQ0MGUtYmMxNi04MDQ4YmQwNjEwOGYjI3RxYlY2T2RlUw==" --execution-mode=synchronous
Error: Pipeline argument validation failed - invalid format: teamwork_tag_id=ZmRkYjNkMDQtYWQ2MS00YjBjLWFmNWEtMjkzMmEyNzdkMmJjIyM2ZWIwOWYwMi03NDVmLTQ0MGUtYmMxNi04MDQ4YmQwNjEwOGYjI3RxYlY2T2RlUw== 
```

**Comment by vhadianto** [comment]
Closing as it was address by https://github.com/turbot/flowpipe/commit/eda4f99816bc3293b3ebe41a2b9d70eca57eeb34
