### ISSUE TITLE
Can I use variables to enable/disable triggers?

### ISSUE THREAD

**Issue by e-gineer** [turbot/flowpipe#167]
Imagine a mod that includes a feature scheduled start / stop of instances, which involves cron triggers.

I'd like to use the mod, but not that specific feature.

Is it possible to disable a trigger somehow through a variable? e.g. an empty cron expression? or a flag?

Perhaps the same question applies for pipelines in general - to disable them from being available to run?

**Comment by vhadianto** [comment]
Added the `enabled` attribute in v0.2.0 

https://flowpipe.io/changelog/flowpipe-cli-v0-2-0
