### ISSUE TITLE
TO DO list

### ISSUE THREAD

**Issue by johnsmyth** [turbot/flowpipe#256]
# Tasks
- ~change `--pipeline-arg` to `--arg`~

- ~change `flowpipe run` to be "serverless" by deafult~
  ~- use `--host` o connect to a server instance instead~

- ~remove `flowpipe service` commands, implemement `flowpipe server`~
  - ~add `--port` to `flowpipe server`.  This is only the port to LISTEN on, not to connect to (which is in the host)~
  - ~add `--listen` to `flowpipe server`~

- !rename `--api-host` to `--host`. ~
  - ~should also include the port to connect to: `http://localhost:7103`~

- ~remove `--api-port`~

- ~change `--execution mode synchronous` to `--detach` (flag/boolean)~
  - only allowed in "server" mode
  - needs more context 

- ~Add `tags`, `documentation` for all top-level resource (`pipelines`, `triggers`, `integrations`)~

- ~`--output` doesnt work - should work for ALL commands~
  - need consistent table view &
  - json for hub introspection

- ~Add `--watch=false` arg to `flowpipe server`~

- ~`flowpipe trigger show` should show all the trigger urls~

- ~Do we need a `--progress` flag???~

- ~implement `FLOWPIPE_MEMORY_MAX` /  `memory_max_mb`~

- Allow short form of ids 
  - display last 6 chars
  - Accept short OR long ids in commands

- query step - dbs other than postgres 
  - [Golang `sql` and `sql/driver` packages](https://github.com/golang/go/wiki/SQLDrivers)
    - mvp - postgres, mysql, sqlite

- query step - passing args (how does this work?)

- ~query trigger~

- sqlite event store

- ~opengraph stuff for flowpipe `mod` (should work like steampipe)~

- ~`base =` in workspaces?~
  - is this easy?

-  allow multiple methods on http trigger

- ~implement workspaces~

- ~reconcile all CLI args / environment variables / workspace options~

- ~container - build from `source`~

# Needs design & prioritization

- do we support `sensitive` on variables, params, or outputs?  how are they handled?

- redact secrets in CLI display 
  - (but allow revealing with `--reveal` flag? `--output reveal`?)

- change the flowpipe metadata from htpp trigger to be returned in the header instead of the body

- execution mode on triggers?  "custom" response body / header from triggers?

- `container` "combined" stdout / stderr

- review flag for mod install on private repo - do we need a flag at all?  can we just attempt both?

- implement telemetry `FLOWPIPE_TELEMETRY`
  - have the env var even if it doesnt do anything

- implement update check - `FLOWPIPE_UPDATE_CHECK`

- implement settable log levels: `FLOWPIPE_LOG_LEVEL`
  - where do these get written?

- Mod update with branches

- remove `--install-dir` 

# Out of scope - open issues for these?

- `flowpipe completion`

- pipes integration:  `flowpipe login`,  PIPES_TOKEN, PIPES_HOST, FLOWPIPE_CLOUD_HOST, FLOWPIPE_CLOUD_TOKEN etc

- `base =`  on triggers?

# Out of scope - Needs design
- `FLOWPIPE_MAX_PARALLEL` ?
- `FLOWPIPE_QUERY_TIMEOUT` ?
- steampipe-specific options?
  - `FLOWPIPE_CACHE_TTL` ?
  - `FLOWPIPE_CACHE` ?
  - can we do these with [Postgres custom options?]( https://www.postgresql.org/docs/14/runtime-config-custom.html)

**Comment by vhadianto** [comment]
Moved to Flowpipe Wiki
