### ISSUE TITLE
improvements to latest cli v0.1.0-beta.202311211218

### ISSUE THREAD

**Issue by vkumbha** [turbot/flowpipe#293]
1. Error message when server is not running.
Thanks for fixing https://github.com/turbot/flowpipe/issues/124. 
With lastest CLI version `Flowpipe v0.1.0-beta.202311211218` in order to run the server you need to do `flowpipe server` so this error message is no longer valid and needs an update.

```
Error: Error executing pipeline - flowpipe service is unreachable.
You can start a local flowpipe server with "cd <mod-directory> && flowpipe service start"
```

2. Can you add an example in the Global Flags for --host? I was trying without the "http://" and couldn't understand what was wrong!
`--host string    API server host, including the port number. Example: --host http://localhost:7103`
```
Usage:
  flowpipe pipeline run <pipeline-name> [flags]

Flags:
      --arg stringArray     Specify the value of a pipeline argument. Multiple --pipeline-arg may be passed.
  -h, --help                help for run
      --log-dir string      The directory path to the log file for the execution. (default "~/.flowpipe/log")
      --output-dir string   The directory path to dump the snapshot file. (default "~/.flowpipe/output")

Global Flags:
      --host string           API server host, including the port number
      --insecure              Skip TLS verification
      --install-dir string    Path to the Config Directory (default "redacted")
      --mod-location string   Path to the workspace working directory (default "redacted")
      --output output         Output format; one of: table, yaml, json (default table)
```

3. Can the --host have a default of `http://localhost:7103`. Feels annoying to include that everytime I run a pipeline. Or can I pass it through environment variables?

**Comment by graza-io** [comment]
1. Updated
2. Example added
3. Because we have local execution, not possible to add a default direct to command, I believe you can specify in your workspace though.
