### ISSUE TITLE
Add support for `source` in step.container

### ISSUE THREAD

**Issue by vkumbha** [turbot/flowpipe#398]
As per docs, step.container can either use `image` or `source`. Looks like source is not implemented yet.

```
$ flowpipe pipeline run container_example
Error: Failed to decode mod:
Source is not yet implemented: container.hellworld
```

Source v/s Image
You must specify either an image or a source but not both. The image will be pulled via standard docker client commands - The image must be publicly accessible or you must docker login to access a private repo. You may instead specify a source in which case a custom image will be built before the step is run. The image will be updated when anything in the source directory changes, and it will be deleted if if the step is deleted.

**Comment by graza-io** [comment]
Added in commit https://github.com/turbot/flowpipe/commit/39837e49606d07f784603a5d1af116eb697e0246
