### ISSUE TITLE
Verify `flowpipe server` output & args

### ISSUE THREAD

**Issue by graza-io** [turbot/flowpipe#452]
- High-level "events" for flowpipe server - pipeline started, pipeline complete, trigger started, etc should be written to STDOUT
  - You cannot specify `--output json` or `--output yaml` for flowpipe server.
  - _Note that if you enable logging, the log entries will be written as json to `stderr` and will also contain the events, so you can effectively get json output if you want it for server logging purposes._

**Comment by graza-io** [comment]
`server` output should look similar to the output of pipeline run but should not be the same.

Things that should be output:
- Startup Information
  - Including some basic information about the mod that is loaded, API url, etc.
  - Information on Triggers that are enabled (& how to action them, url or what schedule / query-events will trigger them)
- Trigger Execution Information
  - Start/End/Errors/etc
  - [VERBOSE] Include payload
- Pipeline Execution Information
  - Start/End/Errors/etc
  - [VERBOSE] optional - Step Start/End/Errors
- Reloads
  - Mod reloads due to code changes, etc
- Failures
- Shutdown Information

**Comment by vhadianto** [comment]
We should also add "Execution ID" on each output entry so we can search it easily in system like GCP Logs Explorer/AWS CloudWatch Logs.
