### ISSUE TITLE
Removed GitHub SHA output redaction

### ISSUE THREAD

**Issue by vhadianto** [turbot/flowpipe#567]
This is not impacting the running of the pipeline, this is only output redaction issue. We should exclude this ID in the redacted string list.

```
[get_file] Output user = {
  "_links": {
    "git": "https://api.github.com/repos/judell/test/git/blobs/REDACTED",
    "html": "https://github.com/judell/test/blob/main/README.md",
    "self": "https://api.github.com/repos/judell/test/contents/README.md?ref=main"
  },
```

**Comment by graza-io** [comment]
Noticed this one should assist with https://github.com/turbot/flowpipe/issues/524 as `container_id` and `trigger_url` are both seemingly affected by this one redaction
