### ISSUE TITLE
Only allow running pipeline on the top level mod and it's top level dependencies

### ISSUE THREAD

**Issue by vhadianto** [turbot/flowpipe#59]
Consider this structure:

```
Mod A
  |
  |---- Mod B
  |           |
  |           |------- Mod C
  |
  |---- Mod X
  |           |
  |           |------- Mod C
```

We should be able to:

1. Run pipelines in Mod A. Using fully qualified name: `a.pipeline.foo` or just `foo`
2. Run pipelines in Mod B and Mod X, but only using fully qualified name
3. We should NOT be able to run pipelines in Mod C.

**Comment by vhadianto** [comment]
@graza-io - can you please quickly check. This may already work as expected but if not it should be a good low hanging fruit.

**Comment by graza-io** [comment]
Created a simple parent pipeline for the GitHub library mod (using one of the flowpipe sample pipelines)

Installed this as a dependency into a test mod entitled `tier3`

```sh
Installed 2 mods:

tier3
└── github.com/*******/flowpipe-mod-parent@v0.0.1
    └── github.com/turbot/flowpipe-mod-github@v0.1.0
```

I can only see pipelines from `tier3` and `parent` mod but not the underlying `github` library mod.

```sh
❯ go run . pipeline list --host local
MOD           NAME                                                     DESCRIPTION
mod.parent    parent.pipeline.list_github_repository_issues_authors    Lists the authors of the issues in a GitHub repository.
mod.tier3     tier3.pipeline.simple
```
