### ISSUE TITLE
Flowpipe v0.2.1

### ISSUE THREAD

**Issue by graza-io** [turbot/flowpipe#613]
#### Changelog

[Flowpipe v0.2.1 Changelog](https://github.com/turbot/flowpipe/blob/v0.2.1/CHANGELOG.md)

### Pipe Fittings
- [x] Pipe Fittings Changelog updated with correct version and date
- [x] `pipe-fittings` tagged with correct final version (ensure you have a clean branch, otherwise the tag will be created on the wrong commit and difficult to revert)

### Flowpipe SDK Go
- [x] `flowpipe-sdk-go` tagged with correct final version (ensure you have a clean branch, otherwise the tag will be created on the wrong commit and difficult to revert)

### Flowpipe

- [x] Flowpipe Changelog updated and reviewed
- [x] Update Flowipe dependency to `flowpipe-go-sdk` to use the relase tag
- [x] Update Flowpipe dependency to `pipe-fittings` to use the relase tag
- [x] Run release build. Do not tag `flowpipe repo``, the workflow will create the tag
- [x] Update Changelog in the Release page (copy and paste from CHANGELOG.md)
- [x] Test Linux install script
- [x] Test Windows install
- [x] Mark release as "latest" (workflow creates pre-release version)
- [x] Merge PR in `@turbot/homebrew-tap` repo to update Turbot Homebrew Tap

### flowpipe.io

- [x] Raise Changelog update to `flowpipe.io`
- [x] Merge Changelog update to `flowpipe.io`

### Post release check & admin
- [x] Test Homebrew install
- [x] Release branches merged to `main` (all three repos `flowpipe`, `flowpipe-go-sdk`, `pipe-fittings`)

**Comment by vhadianto** [comment]
`v0.2.x` branch merged to main. Release completed.
