### ISSUE TITLE
Pipeline execution fails when an input string is passed in double quotes

### ISSUE THREAD

**Issue by misraved** [turbot/flowpipe#791]
**Describe the bug**
When a pipeline's input argument is of the string data type and if it is enclosed inside the double quotes, then the pipeline execution fails.

**Flowpipe version (`flowpipe -v`)**
Example: v0.3.2

**To reproduce**
`flowpipe pipeline run aws.pipeline.tag_resources --arg 'tags={"jane":"doe"}' --arg 'region="us-east-2"' --arg 'resource_arns=["arn:aws:s3:::test"]'` command fails, however, `flowpipe pipeline run aws.pipeline.tag_resources --arg 'tags={"jane":"doe"}' --arg 'region=us-east-2' --arg 'resource_arns=["arn:aws:s3:::test"]'` works correctly.

**Expected behavior**

**Additional context**

**Comment by vhadianto** [comment]
The change is in pipe-fittings: https://github.com/turbot/pipe-fittings/commit/646921f679c0ab2452c7c66aae3b06ca44538cbd

This will be released as part of `v0.4.0`
