### ISSUE TITLE
Should a .flowpipe dir be created if I just run flowpipe trigger list?

### ISSUE THREAD

**Issue by e-gineer** [turbot/flowpipe#808]
I have a generic directory on my machine. It does not contain a flowpipe mod.

I ran `flowpipe trigger list` (mostly because I wanted to see if a new flowpipe version was a available).

I was surprised that it created a `./.flowpipe/flowpipe.db` file? Under what circumstances should we actually create that DB file? I'm surprised a trigger list is enough to do it?

**Comment by vhadianto** [comment]
Right it creates the file at startup. I'll change this to only create when it needs it.

**Comment by vhadianto** [comment]
Fixed in v0.4.3
