### ISSUE TITLE
null JSON value not visible in output on dark mode terminal

### ISSUE THREAD

**Issue by e-gineer** [turbot/flowpipe#829]
Here is what I see:
<img width="228" alt="image" src="https://github.com/turbot/flowpipe/assets/1328145/e3114891-f34c-4bb3-afff-a214a09e9001">

Here is the actual text copied out:
```
[approve] Output result = {
  "label": "Skip",
  "style": null,
  "value": "skip"
}
```

**Comment by graza-io** [comment]
This seems to stem from where we replicated the `go-prettyjson` colors (but we removed the bold):

The code is in [pipe-fittings](https://github.com/turbot/pipe-fittings/blob/main/color/json_formatter.go#L14) where it uses `FgBlack` for the `null` color - comparison against [go-prettyjson here](https://github.com/hokaccha/go-prettyjson/blob/master/prettyjson.go#L53)

> Note: This means it works fine on a light background but default dark background & tango dark make this text invisible (as I'm sure some other themes do)

We could make this "BrightBlack" (aka grey) or one of the other ANSI colors that has more contrast against default black/white backgrounds?
