### ISSUE TITLE
Unable to terminate a process when using flowpipe in interactive mode

### ISSUE THREAD

**Issue by misraved** [turbot/flowpipe#866]
**Describe the bug**
While running flowpipe in the default interactive mode for detect and correct pipelines, the spinner seems to get stuck and using `Ctrl+C` doesn't let me terminate the command/process.

**Flowpipe version (`flowpipe -v`)**
Example: v0.6.0

**To reproduce**
- Clone: https://github.com/turbot/flowpipe-mod-gcp-labels
- Switch: `git switch add-pipelines`
- Run: `flowpipe pipeline run detect_and_correct_dns_managed_zones_with_incorrect_labels`
- Choose `Apply` label
- The spinner gets stuck and even though you press the `Ctrl+c` key, the process does not get terminated

**Expected behavior**
I should be able to terminate a process using the `Ctrl+c` command

**Additional context**

**Comment by graza-io** [comment]
Hm, have a quick fix on the `progress-tweak` branch, not sure if we should output anything in this scenario or not.

**Comment by graza-io** [comment]
Re-opening as previous fix caused other issues.
